const SITE_LIST_TYPE_ID = 20;
const ACCOUNT_LIST_TYPE_ID = 22;
const TRACK_THEME_LIST_TYPE_ID = 23;
const SESSION_LIST_TYPE_ID = 24;
const TRACK_STYLE_TYPE_ID = 30;
const GROUPED_TRACKS_ID = 31;
const HIGHLIGHT_ID = 32;
