import 'package:flutter/material.dart';

Map<String, dynamic> theme_blue = {
  "ref_seq": {
    "light": {
      "color_map": {"A": 4283215696, "T": 4294198070, "C": 4280391411, "G": 4294940672},
      "label_font_size": 10.0
    },
    "dark": {
      "color_map": {"A": 4283215696, "T": 4294198070, "C": 4280391411, "G": 4294940672},
      "label_font_size": 10.0
    }
  },
  "gff": {
    "dark": {
      "feature_group_color": "99333b44",
      "feature_height": 8,
      "label_color": 2332033023,
      "label_font_size": 12,
      "name": "Blue-Dark",
      "show_label": true,
      "track_color": "ff5e5ce6",
      "track_height": 200,
      "track_max_height": {"enabled": true, "value": 500},
      "featureStyles": {
        "gene": {
          "name": 'gene',
          "id": 'gene',
          "alpha": 255,
          "borderColor": "ff9e9e9e",
          "borderWidth": 0,
          "color": "ff0a84ff",
          "height": 1,
          "radius": 3,
          "visible": true,
        },
        "cds": {
          "name": 'CDS',
          "id": 'cds',
          "alpha": 255,
          "borderColor": "ff9e9e9e",
          "borderWidth": 0,
          "color": "ff64d2ff",
          "height": 1,
          "radius": 3,
          "visible": true,
        },
        "exon": {
          "name": 'exon',
          "id": 'exon',
          "alpha": 255,
          "borderColor": "ff64d2ff",
          "borderWidth": 3,
          "color": "99333b44",
          "height": 0.7000000000000001,
          "radius": 3,
          "visible": true,
        },
        "intron": {
          "name": 'intron',
          "id": 'intron',
          "alpha": 200,
          "borderColor": "ff9e9e9e",
          "borderWidth": 0,
          "color": "ff9e9e9e",
          "height": 0.1,
          "radius": 0,
          "visible": true,
        },
        "five_prime_utr": {
          "name": 'five_prime_UTR',
          "id": 'five_prime_utr',
          "alpha": 255,
          "borderColor": "ffff9f0a",
          "borderWidth": 0,
          "color": "00ffd60a",
          "height": 1,
          "radius": 3,
          "visible": true,
        },
        "three_prime_utr": {
          "name": 'three_prime_UTR',
          "id": 'three_prime_utr',
          "alpha": 255,
          "borderColor": "ffff9f0a",
          "borderWidth": 0,
          "color": "00ffd60a",
          "height": 1,
          "radius": 3,
          "visible": true,
        },
        "est_match": {
          "id": "est_match",
          "name": "EST_match",
          "alpha": 255,
          "borderColor": 4294942474,
          "borderWidth": 0.0,
          "color": 4288729831,
          "height": 0.1,
          "radius": 2.0,
          "visible": true,
        },
        "match_part": {
          "id": "match_part",
          "name": "match_part",
          "alpha": 255,
          "borderColor": 4292714250,
          "borderWidth": 0.0,
          "color": 4162304497,
          "height": 1.0,
          "radius": 2.0,
          "visible": true,
        },
        "others": {
          "name": 'others',
          "id": 'others',
          "alpha": 255,
          "borderColor": "ff9e9e9e",
          "borderWidth": 0,
          "color": "ff30d158",
          "height": 1,
          "radius": 3,
          "visible": true,
        },
      },
    },
    "light": {
      "feature_group_color": "7edfe5ed",
      "feature_height": 8,
      "label_color": 2315255808,
      "label_font_size": 12,
      "name": "Blue-Light",
      "show_label": true,
      "track_color": "ff182da3",
      "track_height": 200,
      "track_max_height": {"enabled": true, "value": 500},
      "featureStyles": {
        "gene": {
          "name": "gene",
          "id": "gene",
          "alpha": 200,
          "borderColor": "ff9e9e9e",
          "borderWidth": 0,
          "color": "ff035aa6",
          "height": 1,
          "radius": 3,
          "visible": true,
        },
        "cds": {
          "name": "CDS",
          "id": "cds",
          "alpha": 255,
          "borderColor": "ff9e9e9e",
          "borderWidth": 0,
          "color": "ff40bad5",
          "height": 1,
          "radius": 3,
          "visible": true,
        },
        "exon": {
          "name": "exon",
          "id": "exon",
          "alpha": 126,
          "borderColor": 4282432213,
          "borderWidth": 0.0,
          "color": 2119625952,
          "height": 0.5,
          "radius": 3.0,
          "visible": true,
        },
        "five_prime_utr": {
          "name": "five_prime_UTR",
          "id": "five_prime_utr",
          "alpha": 0,
          "borderColor": 4294754078,
          "borderWidth": 2.0,
          "color": 15717779,
          "height": 1.0,
          "radius": 2.0,
          "visible": true,
        },
        "three_prime_utr": {
          "name": "three_prime_UTR",
          "id": "three_prime_utr",
          "alpha": 255,
          "borderColor": 4294754078,
          "borderWidth": 1.0,
          "color": 16563998,
          "height": 1.0,
          "radius": 2.0,
          "visible": true,
        },
        "intron": {
          "name": "intron",
          "id": "intron",
          "alpha": 200,
          "borderColor": "ff9e9e9e",
          "borderWidth": 0,
          "color": "ff9e9e9e",
          "height": 0.1,
          "radius": 0,
          "visible": true,
        },
        "est_match": {
          "id": "est_match",
          "name": "EST_match",
          "alpha": 255,
          "borderColor": 4294942474,
          "borderWidth": 0.0,
          "color": 4279721713,
          "height": 0.1,
          "radius": 2.0,
          "visible": true,
        },
        "match_part": {
          "id": "match_part",
          "name": "match_part",
          "alpha": 255,
          "borderColor": 4292714250,
          "borderWidth": 0.0,
          "color": 4279356654,
          "height": 1.0,
          "radius": 2.0,
          "visible": true,
        },
        "others": {
          "name": "others",
          "id": "others",
          "alpha": 255,
          "borderColor": "ff9e9e9e",
          "borderWidth": 0,
          "color": "ff038b52",
          "height": 1,
          "radius": 3,
          "visible": true,
        },
      },
    }
  },
  "bam_coverage": {
    "light": {
      "color_map": {"A": 4283215696, "T": 4294198070, "C": 4280391411, "G": 4294940672, "coverage": 4288585374},
      "track_color": 3930739170,
      "track_height": 120.0,
      "density_mode": false
    },
    "dark": {
      "color_map": {"A": 4283215696, "T": 4294198070, "C": 4280391411, "G": 4294940672, "coverage": 4288585374},
      "track_color": 4288585374,
      "track_height": 120.0,
      "density_mode": false
    }
  },
  "bam_reads": {
    "light": {
      "color_map_strand_default": {
        "fwd": Color(0xFFec8b8b),
        "rev": Color(0xff8f8fd8),
        "fwd_missing_mate": Color(0xFFd11919),
        "rev_missing_mate": Color(0xFF1919d1),
        "fwd_not_proper": Color(0xFFecc8cb),
        "rev_not_proper": Color(0xFFbebed8),
        "fwd_diff_chr": Color(0xFF000000),
        "rev_diff_chr": Color(0xFF969696),
        "no_strand": Color(0xFF999999),
      },
      "color_map_no_color": {"+": Color(0xFF969696), "-": Color(0xFF969696)},
      "color_map_strand": {"+": 3438254746, "-": 3432041209},
      "color_map_mapping_quality": {"start": 3438254746, "end": 3432041209},
      "color_map_insert_size": {"start": 3438254746, "end": 3432041209},
      "color_map_pair_orientation": {'normal': Color(0xD2D2D2), "LR": Color(0xff999999), "LL": Color(0xff70AD47), 'RR': Color(0xff00007F), 'RL': Color(0xff007F7F)},
      "color_map_XS_tag": {"start": 3438254746, "end": 3432041209},
      "color_map_TS_tag": {"start": 3438254746, "end": 3432041209},
      "color_map_modifications": {"modify": Colors.red, "+": 3438254746, "-": 3432041209},
      "color_map_methylation": {"melthy": Colors.red, "un-melthy": Colors.blueAccent, "+": 3438254746, "-": 3432041209},
      "track_color": 4280391411,
      "track_max_height": {'enabled': true, 'value': 300},
      "feature_height": 8.0,
      "label_font_size": 12.0,
      "label_color": Colors.black54,
      "feature_group_color": 1296871248,
      "show_label": true
    },
    "dark": {
      "color_map_strand_default": {
        "fwd": Color(0xFFec8b8b),
        "rev": Color(0xff8f8fd8),
        "fwd_missing_mate": Color(0xFFd11919),
        "rev_missing_mate": Color(0xFF1919d1),
        "fwd_not_proper": Color(0xFFecc8cb),
        "rev_not_proper": Color(0xFFbebed8),
        "fwd_diff_chr": Color(0xFF000000),
        "rev_diff_chr": Color(0xFF969696),
        "no_strand": Color(0xFF999999),
      },
      "color_map_no_color": {"+": Color(0xFF969696), "-": Color(0xFF969696)},
      "color_map_strand": {"+": 3438254746, "-": 3432041209},
      "color_map_mapping_quality": {"start": 3438254746, "end": 3432041209},
      "color_map_insert_size": {"start": 3438254746, "end": 3432041209},
      "color_map_pair_orientation": {'normal': Color(0xD2D2D2), "LR": Color(0xff999999), "LL": Color(0xff70AD47), 'RR': Color(0xff00007F), 'RL': Color(0xff007F7F)},
      "color_map_XS_tag": {"start": 3438254746, "end": 3432041209},
      "color_map_TS_tag": {"start": 3438254746, "end": 3432041209},
      "color_map_modifications": {"modify": Colors.red, "+": 3438254746, "-": 3432041209},
      "color_map_methylation": {"melthy": Colors.red, "un-melthy": Colors.blueAccent, "+": 3438254746, "-": 3432041209},
      "track_color": 4280391411,
      "track_max_height": {'enabled': true, 'value': 300},
      "feature_height": 8.0,
      "label_font_size": 12.0,
      "label_color": Colors.white54,
      "feature_group_color": 1296871248,
      "show_label": true
    }
  },
  "bigwig": {
    "light": {
      "color_map": {"+": 4279603682, "-": 4294198070},
      "track_height": 80.0,
      "density_mode": false
    },
    "dark": {
      "color_map": {"+": 4279603682, "-": 4294198070},
      "track_height": 80.0,
      "density_mode": false
    }
  },
  "vcf_sample": {
    "light": {
      "color_map": {"0": 4288585374, "1": 4278430196, "2": 4287349578},
      "track_max_height": {'enabled': true, 'value': 200},
      "track_height": 120.0,
      "feature_height": 12.0,
      "label_font_size": 12.0,
      "label_color": Colors.black54,
      "feature_group_color": 1296871248,
      "show_label": true,
      "track_color": 4280391411
    },
    "dark": {
      "color_map": {"0": 4288585374, "1": 4278430196, "2": 4287349578},
      "track_max_height": {'enabled': true, 'value': 200},
      "track_height": 120.0,
      "feature_height": 12.0,
      "label_font_size": 12.0,
      "label_color": Colors.white54,
      "feature_group_color": 1296871248,
      "show_label": true,
      "track_color": 4280391411
    }
  },
  "vcf_coverage": {
    "light": {
      "track_max_height": {'enabled': true, 'value': 300},
      "track_height": 120.0,
      "feature_height": 12.0,
      "label_font_size": 12.0,
      "label_color": Colors.black54,
      "show_label": true,
      "track_color": 4280607787,
      "feature_group_color": 1841877961,
      "color_map": {
        "SNV": Colors.purpleAccent,
        "SV": Colors.deepOrangeAccent,
        "INDEL": Colors.lightGreen,
        "MNV": Colors.blue,
      },
    },
    "dark": {
      "track_max_height": {'enabled': true, 'value': 300},
      "track_height": 120.0,
      "feature_height": 12.0,
      "label_font_size": 12.0,
      "label_color": Colors.white54,
      "show_label": true,
      "track_color": 4280391411,
      "feature_group_color": 1841877961,
      "color_map": {
        "SNV": Colors.purpleAccent,
        "SV": Colors.deepOrangeAccent,
        "INDEL": Colors.lightGreen,
        "MNV": Colors.blueAccent,
      },
    },
  },
  "methylation": {
    "light": {
      "color_map": {"CG": 4279603682, "CHG": 4294940672, "CHH": 4288423856, "deeps": 4288585374},
      "track_height": 120.0,
      "density_mode": false
    },
    "dark": {
      "color_map": {"CG": 4279603682, "CHG": 4294940672, "CHH": 4288423856, "deeps": 4288585374},
      "track_height": 120.0,
      "density_mode": false
    }
  },
  "hic": {
    "light": {
      "track_max_height": {'enabled': true, 'value': 300},
      "custom_max_value": {'enabled': false, 'value': 100},
      "custom_min_value": {'enabled': false, 'value': 1},
      "track_color": 4280391411,
      "hic_display_mode": 0,
    },
    "dark": {
      "track_max_height": {'enabled': true, 'value': 300},
      "custom_max_value": {'enabled': false, 'value': 100},
      "custom_min_value": {'enabled': false, 'value': 1},
      "track_color": 4280391411,
      "hic_display_mode": 0,
    },
  },
  "interactive": {
    "light": {
      "track_height": 200.0,
      "custom_max_value": {'enabled': false, 'value': 100},
      "custom_min_value": {'enabled': false, 'value': 1},
      "track_color": 4280391411,
      "relation_display_mode": 0,
    },
    "dark": {
      "track_height": 200.0,
      "custom_max_value": {'enabled': false, 'value': 100},
      "custom_min_value": {'enabled': false, 'value': 1},
      "track_color": 4280391411,
      "relation_display_mode": 0,
    }
  },
  // "single_cell_exp": {
  //   "light": {
  //     "color_map": {},
  //     "feature_height": 40.0,
  //     "show_label": true,
  //     "label_font_size": 12.0,
  //     "label_color": Colors.black54,
  //     "show_legends": false,
  //     "bar_width": 4.0,
  //   },
  //   "dark": {
  //     "color_map": {},
  //     "feature_height": 40.0,
  //     "show_label": true,
  //     "label_font_size": 12.0,
  //     "label_color": Colors.white54,
  //     "show_legends": false,
  //     "bar_width": 4.0,
  //   }
  // },
  "peak": {
    "light": {
      'track_color': Colors.blue,
      'track_max_height': {'enabled': false, 'value': 300},
      'feature_height': 8.0,
      'label_font_size': 12.0,
      'label_color': Colors.black54,
      'show_label': true,
    },
    "dark": {
      'track_color': Colors.blue,
      'track_max_height': {'enabled': false, 'value': 300},
      'feature_height': 8.0,
      'label_font_size': 12.0,
      'label_color': Colors.white54,
      'show_label': true,
    },
  },
  // "sc_co_access": {
  //   "light": {
  //     'track_color': Colors.lightBlue,
  //     'track_height': 100.0,
  //     'custom_min_value': {'enabled': false, 'value': 0},
  //     'custom_max_value': {'enabled': false, 'value': 1},
  //   },
  //   "dark": {
  //     'track_color': Colors.lightBlue,
  //     'track_height': 100.0,
  //     'custom_min_value': {'enabled': false, 'value': 0},
  //     'custom_max_value': {'enabled': false, 'value': 1},
  //   },
  // },
  // "sc_group_coverage": {
  //   "light": {
  //     'track_height': 50.0,
  //     'track_max_height': {'enabled': true, 'value': 500.0},
  //     'label_font_size': 12.0,
  //     'label_color': Colors.black54,
  //     'show_label': true,
  //   },
  //   "dark": {
  //     'track_height': 50.0,
  //     'track_max_height': {'enabled': true, 'value': 500.0},
  //     'label_font_size': 12.0,
  //     'label_color': Colors.white54,
  //     'show_label': true,
  //   },
  // },
  "bed": {
    "light": {
      'track_max_height': {'enabled': false, 'value': 300},
      'track_height': 120.0,
      'feature_height': 12.0,
      'label_font_size': 12.0,
      'label_color': Colors.black54,
      'show_label': true,
      'track_color': Colors.blue,
      'feature_group_color': Color(0x6dc8d3c9),
      "featureStyles": {
        "line": {
          "name": "line",
          "id": "line",
          "color": Color(0xff575857),
          "alpha": 255,
          "visible": true,
          "height": .1,
          "radius": 0,
          "borderWidth": 0,
          "borderColor": "ff9e9e9e",
        },
        "base": {
          "name": "base",
          "id": "base",
          "color": Color(0xff2a9333),
          "alpha": 255,
          "visible": true,
          "height": .8,
          "radius": 2,
          "borderWidth": 0,
          "borderColor": "ff9e9e9e",
        },
        "thick": {
          "name": "thick",
          "id": "thick",
          "color": Color(0x00000000),
          "alpha": 0,
          "visible": true,
          "height": 0.5,
          "radius": 0,
          "borderWidth": 0,
          "borderColor": "ff9e9e9e",
        },
        "block": {
          "name": "block",
          "id": "block",
          "color": Color(0xd7e28529),
          "alpha": 255,
          "visible": true,
          "height": .8,
          "radius": 3,
          "borderWidth": 0,
          "borderColor": "ff9e9e9e",
        },
      },
    },
    "dark": {
      'track_max_height': {'enabled': false, 'value': 300},
      'track_height': 120.0,
      'feature_height': 12.0,
      'label_font_size': 12.0,
      'label_color': Colors.white54,
      'show_label': true,
      'track_color': Colors.blue,
      'feature_group_color': Color(0x6dc8d3c9),
      "featureStyles": {
        "line": {
          "name": "line",
          "id": "line",
          "color": Color(0xFF9E9E9E),
          "alpha": 255,
          "visible": true,
          "height": .1,
          "radius": 0,
          "borderWidth": 0,
          "borderColor": "ff9e9e9e",
        },
        "base": {
          "name": "base",
          "id": "base",
          "color": Color(0xff2a9333),
          "alpha": 255,
          "visible": true,
          "height": .8,
          "radius": 2,
          "borderWidth": 0,
          "borderColor": "ff9e9e9e",
        },
        "thick": {
          "name": "thick",
          "id": "thick",
          "color": Color(0x00000000),
          "alpha": 0,
          "visible": true,
          "height": 0.5,
          "radius": 0,
          "borderWidth": 0,
          "borderColor": "ff9e9e9e",
        },
        "block": {
          "name": "block",
          "id": "block",
          "color": Color(0xd7e28529),
          "alpha": 255,
          "visible": true,
          "height": .8,
          "radius": 3,
          "borderWidth": 0,
          "borderColor": "ff9e9e9e",
        },
      },
    },
  },
  "eqtl": {
    "light": {
      'track_height': 80.0,
      'track_max_height': {'enabled': true, 'value': 200.0},
      'track_color': Colors.blue,
      'custom_max_value': {'enabled': true, 'value': 0.05},
      'value_scale_type': 2,
    },
    "dark": {
      'track_height': 80.0,
      'track_max_height': {'enabled': true, 'value': 200.0},
      'track_color': Colors.blueAccent,
      'custom_max_value': {'enabled': true, 'value': 0.05},
      'value_scale_type': 2,
    },
  },
};
